data:extend({

------------------------------------------------------------------ CalciumOxigenHigidrogen

  {
    type = "item",
    name = "quicklime",
	icon = "__shchierbin__/graphics/item/quicklime.png",
	icon_size = 64,
    subgroup = "shchierbin",
    order = "a",
	stack_size = 50,
    weight = 2*kg,
  },
  {
    type = "item",
    name = "slaked-lime",
	icon = "__shchierbin__/graphics/item/slaked-lime.png",
	icon_size = 64,
    subgroup = "shchierbin",
    order = "b",
	stack_size = 50,
    weight = 2*kg,
  },
  {
    type = "item",
    name = "calcium",
	icon = "__shchierbin__/graphics/item/calcium.png",
	icon_size = 64,
    subgroup = "shchierbin",
    order = "c",
	stack_size = 100,
    weight = 2*kg,
    spoil_ticks = 15 * minute,
    spoil_result = "quicklime"
  },
------------------------------------------------------------------ chlor
    {
    type = "item",
    name = "salt",
	icon = "__shchierbin__/graphics/item/salt.png",
	icon_size = 64,
    subgroup = "shchierbin",
    order = "d",
	stack_size = 50,
    weight = 2*kg,
  },
------------------------------------------------------------------ vanadium-ore
  {
    type = "item",
    name = "vanadium-ore",
	icon = "__shchierbin__/graphics/item/vanadium-ore.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "a",
	stack_size = 50,
    weight = 2*kg,
  },{
    type = "item",
    name = "vanadium-concetrate",
	icon = "__shchierbin__/graphics/item/vanadium-concetrate.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "b",
	stack_size = 50,
    weight = 4*kg,
  },{
    type = "item",
    name = "vanadium-oxide",
	icon = "__shchierbin__/graphics/item/vanadium-oxide.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "c",
	stack_size = 50,
    weight = 4*kg,
  },
------------------------------------------------------------------ vanadium
  {
    type = "item",
    name = "vanadium-dust",
	icon = "__shchierbin__/graphics/item/vanadium-dust.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "d",
	stack_size = 50,
    weight = 2.5*kg,
  },{
    type = "item",
    name = "vanadium-plate",
	icon = "__shchierbin__/graphics/item/vanadium-plate.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "e",
	stack_size = 100,
    weight = 2*kg,
  },
------------------------------------------------------------------ vanadium steel and component
  {
    type = "item",
    name = "ferrovanadium",
	icon = "__shchierbin__/graphics/item/ferrovanadium.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "f",
	stack_size = 50,
    weight = 4*kg,
  },{
    type = "item",
    name = "vanadium-steel-plate",
	icon = "__shchierbin__/graphics/item/vanadium-steel-plate.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "g",
	stack_size = 100,
    weight = 2.5*kg,
  },{
    type = "item",
    name = "vanadium-oxide-catalyst",
	icon = "__shchierbin__/graphics/item/vanadium-oxide-catalyst.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "k",
	stack_size = 100,
    weight = 2.5*kg,
  },{
    type = "item",
    name = "vanadium-lithium-battery",
	icon = "__shchierbin__/graphics/item/vanadium-lithium-battery.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "i",
	stack_size = 100,
    weight = 2.5*kg,
  },{
    type = "item",
    name = "vanadium-electro-engine-unit",
	icon = "__shchierbin__/graphics/item/vanadium-electro-engine-unit.png",
	icon_size = 64,
    subgroup = "vanadium",
    order = "j",
	stack_size = 50,
    weight = 4*kg,
  }
  
})
